// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: helloworld/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_helloworld_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应
type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_helloworld_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 登出请求
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_helloworld_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{2}
}

// 登出响应
type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_helloworld_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取用户信息请求
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_helloworld_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{4}
}

// 获取用户信息响应
type GetUserInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoReply) Reset() {
	*x = GetUserInfoReply{}
	mi := &file_helloworld_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReply) ProtoMessage() {}

func (x *GetUserInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReply.ProtoReflect.Descriptor instead.
func (*GetUserInfoReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserInfoReply) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetUserInfoReply) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// 管理员请求
type AdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRequest) Reset() {
	*x = AdminRequest{}
	mi := &file_helloworld_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRequest) ProtoMessage() {}

func (x *AdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRequest.ProtoReflect.Descriptor instead.
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{6}
}

// 管理员响应
type AdminReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	AdminInfo     string                 `protobuf:"bytes,2,opt,name=admin_info,json=adminInfo,proto3" json:"admin_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminReply) Reset() {
	*x = AdminReply{}
	mi := &file_helloworld_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminReply) ProtoMessage() {}

func (x *AdminReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminReply.ProtoReflect.Descriptor instead.
func (*AdminReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *AdminReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminReply) GetAdminInfo() string {
	if x != nil {
		return x.AdminInfo
	}
	return ""
}

// 编辑用户请求
type EditUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewUsername   string                 `protobuf:"bytes,2,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserRequest) Reset() {
	*x = EditUserRequest{}
	mi := &file_helloworld_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserRequest) ProtoMessage() {}

func (x *EditUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserRequest.ProtoReflect.Descriptor instead.
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *EditUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EditUserRequest) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

// 编辑用户响应
type EditUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserReply) Reset() {
	*x = EditUserReply{}
	mi := &file_helloworld_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserReply) ProtoMessage() {}

func (x *EditUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserReply.ProtoReflect.Descriptor instead.
func (*EditUserReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *EditUserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 公开信息请求
type PublicInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicInfoRequest) Reset() {
	*x = PublicInfoRequest{}
	mi := &file_helloworld_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicInfoRequest) ProtoMessage() {}

func (x *PublicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicInfoRequest.ProtoReflect.Descriptor instead.
func (*PublicInfoRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{10}
}

// 公开信息响应
type PublicInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicInfoReply) Reset() {
	*x = PublicInfoReply{}
	mi := &file_helloworld_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicInfoReply) ProtoMessage() {}

func (x *PublicInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicInfoReply.ProtoReflect.Descriptor instead.
func (*PublicInfoReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *PublicInfoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PublicInfoReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_helloworld_v1_user_proto protoreflect.FileDescriptor

const file_helloworld_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x18helloworld/v1/user.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"U\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\x0f\n" +
	"\rLogoutRequest\"'\n" +
	"\vLogoutReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x14\n" +
	"\x12GetUserInfoRequest\"\x7f\n" +
	"\x10GetUserInfoReply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\"\x0e\n" +
	"\fAdminRequest\"E\n" +
	"\n" +
	"AdminReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"admin_info\x18\x02 \x01(\tR\tadminInfo\"M\n" +
	"\x0fEditUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fnew_username\x18\x02 \x01(\tR\vnewUsername\")\n" +
	"\rEditUserReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x13\n" +
	"\x11PublicInfoRequest\"E\n" +
	"\x0fPublicInfoReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xd4\x04\n" +
	"\x04User\x12V\n" +
	"\x05Login\x12\x1b.helloworld.v1.LoginRequest\x1a\x19.helloworld.v1.LoginReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/login\x12W\n" +
	"\x06Logout\x12\x1c.helloworld.v1.LogoutRequest\x1a\x1a.helloworld.v1.LogoutReply\"\x13\x82\xd3\xe4\x93\x02\r\"\v/api/logout\x12i\n" +
	"\vGetUserInfo\x12!.helloworld.v1.GetUserInfoRequest\x1a\x1f.helloworld.v1.GetUserInfoReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/user/info\x12a\n" +
	"\tAdminOnly\x12\x1b.helloworld.v1.AdminRequest\x1a\x19.helloworld.v1.AdminReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/admin/dashboard\x12c\n" +
	"\bEditUser\x12\x1e.helloworld.v1.EditUserRequest\x1a\x1c.helloworld.v1.EditUserReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/user/edit\x12h\n" +
	"\n" +
	"PublicInfo\x12 .helloworld.v1.PublicInfoRequest\x1a\x1e.helloworld.v1.PublicInfoReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/public/infoB%Z#kratos-example/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_user_proto_rawDescOnce sync.Once
	file_helloworld_v1_user_proto_rawDescData []byte
)

func file_helloworld_v1_user_proto_rawDescGZIP() []byte {
	file_helloworld_v1_user_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_user_proto_rawDesc), len(file_helloworld_v1_user_proto_rawDesc)))
	})
	return file_helloworld_v1_user_proto_rawDescData
}

var file_helloworld_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_helloworld_v1_user_proto_goTypes = []any{
	(*LoginRequest)(nil),       // 0: helloworld.v1.LoginRequest
	(*LoginReply)(nil),         // 1: helloworld.v1.LoginReply
	(*LogoutRequest)(nil),      // 2: helloworld.v1.LogoutRequest
	(*LogoutReply)(nil),        // 3: helloworld.v1.LogoutReply
	(*GetUserInfoRequest)(nil), // 4: helloworld.v1.GetUserInfoRequest
	(*GetUserInfoReply)(nil),   // 5: helloworld.v1.GetUserInfoReply
	(*AdminRequest)(nil),       // 6: helloworld.v1.AdminRequest
	(*AdminReply)(nil),         // 7: helloworld.v1.AdminReply
	(*EditUserRequest)(nil),    // 8: helloworld.v1.EditUserRequest
	(*EditUserReply)(nil),      // 9: helloworld.v1.EditUserReply
	(*PublicInfoRequest)(nil),  // 10: helloworld.v1.PublicInfoRequest
	(*PublicInfoReply)(nil),    // 11: helloworld.v1.PublicInfoReply
}
var file_helloworld_v1_user_proto_depIdxs = []int32{
	0,  // 0: helloworld.v1.User.Login:input_type -> helloworld.v1.LoginRequest
	2,  // 1: helloworld.v1.User.Logout:input_type -> helloworld.v1.LogoutRequest
	4,  // 2: helloworld.v1.User.GetUserInfo:input_type -> helloworld.v1.GetUserInfoRequest
	6,  // 3: helloworld.v1.User.AdminOnly:input_type -> helloworld.v1.AdminRequest
	8,  // 4: helloworld.v1.User.EditUser:input_type -> helloworld.v1.EditUserRequest
	10, // 5: helloworld.v1.User.PublicInfo:input_type -> helloworld.v1.PublicInfoRequest
	1,  // 6: helloworld.v1.User.Login:output_type -> helloworld.v1.LoginReply
	3,  // 7: helloworld.v1.User.Logout:output_type -> helloworld.v1.LogoutReply
	5,  // 8: helloworld.v1.User.GetUserInfo:output_type -> helloworld.v1.GetUserInfoReply
	7,  // 9: helloworld.v1.User.AdminOnly:output_type -> helloworld.v1.AdminReply
	9,  // 10: helloworld.v1.User.EditUser:output_type -> helloworld.v1.EditUserReply
	11, // 11: helloworld.v1.User.PublicInfo:output_type -> helloworld.v1.PublicInfoReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_v1_user_proto_init() }
func file_helloworld_v1_user_proto_init() {
	if File_helloworld_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_user_proto_rawDesc), len(file_helloworld_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_user_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_user_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_user_proto_msgTypes,
	}.Build()
	File_helloworld_v1_user_proto = out.File
	file_helloworld_v1_user_proto_goTypes = nil
	file_helloworld_v1_user_proto_depIdxs = nil
}
